# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51e6ee1995c68bb6fc8d99d466bb7da80fc102ced85c13da7cc90abfc70615a0e7b343968511a317b506aa9a8561165a0219a3284f4e1d4f7c78ffef166daedf
  stripe_publishable_key: pk_test_mgotCtnX4wfBFJ5ZYA1nMLy0 
  stripe_secret_key: sk_test_hlsmZJ5B2LRPE7gSxS2BU0sf
  stripe_client_id:  ca_9fYuxXmDkOIp464kY6d3G9NmkVFAg8EA

  FACEBOOK_APP_ID: 156097404982686
  FACEBOOK_APP_SECRET: 5a4e28a52d27c6a574af5574812d6764

  GOOGLE_APP_ID: 945288453396-icb2h4dtb8clsfm8evafgkvu4auhou0b.apps.googleusercontent.com
  GOOGLE_APP_SECRET: e-juGr50Jc04gWGZUnMrqmEp

test:
  secret_key_base: 51c3e47b69b26e33028df5fc413142a4e75c8381fc5129f372af9fcbb97f4108f73645bc841a3c79691c34a193b109477e0f78642cc852de22781626d00d443b

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  stripe_publishable_key: pk_test_mgotCtnX4wfBFJ5ZYA1nMLy0 
  stripe_secret_key: sk_test_hlsmZJ5B2LRPE7gSxS2BU0sf
  stripe_client_id:  ca_9fYuxXmDkOIp464kY6d3G9NmkVFAg8EA
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
